# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.cache/wt [current_project]
set_property parent.project_path /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/imports/Downloads/Decoder.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/imports/Downloads/Directions.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/imports/Downloads/Idles.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/imports/Downloads/PmodKYPD.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/new/benja.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/imports/Downloads/clk_mgmt.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/imports/Downloads/code_translate.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/new/decider.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/new/elevator_mux.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/new/led_controler.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/new/mov_stop.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/new/mux_membrana.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/new/pisosAn.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/new/request_mux.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/imports/new/sevenseg.v
  /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/sources_1/new/main.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/constrs_1/imports/constrs_1/Bays3.xdc
set_property used_in_implementation false [get_files /opt/Xilinx/Vivado/2018.2/bin/Exp3Elevators/Exp3Elevators.srcs/constrs_1/imports/constrs_1/Bays3.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
